### ISSUE TITLE
What about multiple home-dirs?

### ISSUE THREAD

**Issue by peterjaap** [dambrogia/oh-my-zsh-plugin-magento-2#1]
We're an agency so I have about 20 projects checked out. How do I work with this and multiple projects?

**Comment by dambrogia** [comment]
Hi @peterjaap! apologies for the delay i just noticed your issue.

There are [two files](https://github.com/dambrogia/oh-my-zsh-plugin-magento-2/blob/master/magento-2.plugin.zsh#L3) that store your settings. One for your current magento root directory and one for your cached version of your autocomplete.

To set your project root use the [`m2:set_root <full_path_to_project_root>`](https://github.com/dambrogia/oh-my-zsh-plugin-magento-2/blob/master/magento-2.plugin.zsh#L36). If you swap magento projects you'll need to update the project root for the `m2` tool.

Similarly, your cached version of your autocomplete can be updated by running `m2:set_autocomplete`. 

Running the `m2:set_root` on the fly by recursively traversing up the directory tree and looking for `bin/magento` has been a thought of mine. But I'm torn on that decision because I think it should be the users decision on what root/autocomplete is set when the command is run rather than automatically configured for them. I'm not sure if that is a popular opinion or not.

It was brought up in the original [reddit post](https://www.reddit.com/r/Magento/comments/9x2kad/oh_my_zsh_plugin_for_magento_2/) when I made the repo.

**Comment by peterjaap** [comment]
Ok thanks! Unfortunately manually swapping isn't an option for me since I sometimes work on 5-10 projects on a single day.
